image: gitpod/workspace-full:latest

tasks:
  - init: mvn -DskipTests -q clean package
  - command: mvn -Dspring-boot.run.profiles=default -Dspring-boot.run.arguments="--spring.profiles.active=default" spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions: []

# Automatically open the application and H2 console and Swagger UI
github:
  prebuilds:
    enabled: true

# Open URLs after start (Gitpod supports opening ports as preview)
openMode: tab
